"""Shared DistillServe data contracts.

Every type that crosses a process boundary (HTTP response, SSE frame, worker
message) is defined here exactly once. The frontend consumes generated
TypeScript emitted from these models by ``make schemas``, which is what keeps
`apps/web` from re-declaring — and drifting from — the backend's shapes.
"""

from distillserve_schemas.chat import (
    ChatCompletionChoice,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionDelta,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatMessage,
    ChatRole,
    CostBreakdown,
    DistillServeMetadata,
    GatewayError,
    GatewayErrorBody,
    GenerationMetrics,
    RouteDecision,
    RoutePolicy,
    RouteTarget,
    TokenUsage,
)
from distillserve_schemas.platform import (
    DeploymentMode,
    HealthStatus,
    LivenessResponse,
    ReadinessCheck,
    ReadinessResponse,
    RuntimeEnvironment,
    ServiceIdentity,
)
from distillserve_schemas.telemetry import (
    STAGE_TRAFFIC,
    Adapter,
    AdversarialResult,
    ClusterEvent,
    ClusterEventKind,
    EvalReport,
    GpuNode,
    GpuState,
    JudgeResult,
    ModelVersion,
    ParetoPoint,
    Rollout,
    RolloutEvent,
    RolloutSLI,
    RolloutStage,
    ServingSnapshot,
    SliceScore,
    SLIStatus,
    TenantUsage,
    TimeSeries,
    TimeSeriesPoint,
)

__all__ = [
    "STAGE_TRAFFIC",
    "Adapter",
    "AdversarialResult",
    "ChatCompletionChoice",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "ChatCompletionDelta",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatMessage",
    "ChatRole",
    "ClusterEvent",
    "ClusterEventKind",
    "CostBreakdown",
    "DeploymentMode",
    "DistillServeMetadata",
    "EvalReport",
    "GatewayError",
    "GatewayErrorBody",
    "GenerationMetrics",
    "GpuNode",
    "GpuState",
    "HealthStatus",
    "JudgeResult",
    "LivenessResponse",
    "ModelVersion",
    "ParetoPoint",
    "ReadinessCheck",
    "ReadinessResponse",
    "Rollout",
    "RolloutEvent",
    "RolloutSLI",
    "RolloutStage",
    "RouteDecision",
    "RoutePolicy",
    "RouteTarget",
    "RuntimeEnvironment",
    "SLIStatus",
    "ServiceIdentity",
    "ServingSnapshot",
    "SliceScore",
    "TenantUsage",
    "TimeSeries",
    "TimeSeriesPoint",
    "TokenUsage",
]
